
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_app
    depends_on:
      - db
    command: ["python", "main.py"]
    networks:
      - app-tier

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-tier

volumes:
  postgres_data:

networks:
  app-tier:
    driver: bridge